const blockedStockes = ['ABVKS'    , 'AGESA'    , 'AKSFA'    , 'AKFK'     , 'AKM AKMEN', 'AKBNK'    , 
                        'AKCKM'    , 'AKDFA'    , 'AKGRT'    , 'AKTVK'    , 'AFB AKTIF', 'ALBRK ALK', 
                        'ALFIN'    , 'ALJF'     , 'ALQ ALROS', 'ALNUS ANC', 'ALNTF ANF', 'ANSGR'    , 
                        'ANHYT'    , 'ARSVY'    , 'ATAVK'    , 'ATLFA'    , 'ATLAS'    , 'A1CAP ACP', 
                        'BIENF'    , 'BRKT'     , 'BLKOM'    , 'BRGFK'    , 'BRKVY'    , 'BNPPI'    , 
                        'BLS BLSMD', 'BSRFK'    , 'CRDFA'    , 'CAGFA'    , 'CLDNM'    , 'CLKMT'    , 
                        'DVRLK'    , 'DYBNK'    , 'DGRVK'    , 'DENFA'    , 'DNFIN'    , 'DZY DZYMK', 
                        'DENIZ DNZ', 'DSTKF'    , 'DTBMK'    , 'DTRND'    , 'DFKTR'    , 'DNYVA'    , 
                        'EKER'     , 'EKOFA'    , 'EKOVR'    , 'EMIRV'    , 'EKTVK'    , 'EMVAR'    , 
                        'ERGLI'    , 'EUKYO'    , 'EUYO'     , 'ETYAT'    , 'FSDAT'    , 'FIBAF'    , 
                        'FBB FBBNK', 'GAPIN'    , 'GARFA'    , 'GARFL'    , 'GRNYO'    , 'GEDIK'    , 
                        'GLCVY'    , 'GLB GLBMD', 'GGBVK'    , 'GSIPD'    , 'HALKF'    , 'HALKI HLY', 
                        'HDFFL'    , 'HDFVK'    , 'HDFYB HYB', 'HEPFN'    , 'HLVKS'    , 'HUZFA'    , 
                        'ICB ICBCT', 'IAZ INVAZ', 'INALR'    , 'INFO IYF' , 'ISTFK'    , 'ISFAK'    , 
                        'ISFIN'    , 'ISMEN IYM', 'ISYAT'    , 'KLVKS'    , 'KATVK'    , 'KNTFA'    , 
                        'KFKTF'    , 'KOCFN'    , 'KORTS'    , 'KTKVK'    , 'KTSVK'    , 'LVTVK'    , 
                        'LIDFA'    , 'MRBAS MRS', 'MRMAG'    , 'MEKMD MSA', 'MRBKF'    , 'MBFTR'    , 
                        'MSY MSYBN', 'MNGFA'    , 'NRHOL'    , 'NRLIN'    , 'NURVK'    , 'NRBNK NYB', 
                        'OPET'     , 'ORFIN'    , 'OMD OSMEN', 'OTOKC'    , 'OTOSR'    , 'OYA OYYAT', 
                        'OYAYO'    , 'PRFFK'    , 'PBT PBTR' , 'QNBFF'    , 'QNBFK'    , 'QNBVK'    ,
                        'QUFIN'    , 'QYATB YBQ', 'QYHOL'    , 'RAYSG'    , 'FIN QNBTR', 'QNBFF'    , 
                        'SARTN'    , 'SZUKI'    , 'SMRFA'    , 'SMRVA'    , 'SEKFK'    , 'SKY SKYMD',
                        'SEK SKBNK', 'TAC TCRYT', 'TAMFA'    , 'DRPHN'    , 'TEBFA'    , 'TEBCE'    ,
                        'TRFFA'    , 'TAE TRBNK', 'TERA TRA' , 'TFNVK'    , 'TIMUR'    , 'TRYKI'    ,
                        'TRMEN TVM', 'TRKFN'    , 'TBA TRKSH', 'TRKNT'    , 'GARAN TGB', 'HALKB THL',
                        'EXIMB THR', 'ISATR ISBTR ISCTR ISKUR TIB'        , 'KLN KLNMA', 'TSK TSKB' , 
                        'TURSG'    , 'TVB VAKBN', 'TV8TV'    , 'ULUFA'    , 'VAKFA'    , 'VAKFN'    , 
                        'VKFYO'    , 'VAKVK'    , 'VDFFA'    , 'VDFLO'    , 'VDFAS'    , 'YKFKT'    ,
                        'YKFIN'    , 'YKR YKYAT', 'YKB YKBNK', 'YAT YFMEN', 'YATVK'    , 'ZKBVK'    ,  'ZKBVR', '3'];

export const blockedStockSet = new Set(blockedStockes);