export default ['ABVKS'    , 'AGESA'    , 'AKSFA'    , 'AKFK'     , 'AKM AKMEN', 'AKBNK'    , 
                'AKCKM'    , 'AKDFA'    , 'AKGRT'    , 'AKTVK'    , 'AFB AKTIF', 'ALBRK ALK', 
                'ALFIN'    , 'ALJF'     , 'ALQ ALROS', 'ALNUS ANC', 'ALNTF ANF', 'ANSGR'    , 
                'ANHYT'    , 'ATAVK'    , 'ATLFA'    , 'ATLAS'    , 'A1CAP ACP', 'BRKT'     , 
                'BLKOM'    , 'BRGFK'    , 'BRKVY'    , 'BNPPI'    , 'BLS BLSMD', 'BSRFK'    , 
                'CRDFA'    , 'CAGFA'    , 'CLDNM'    , 'CLKMT'    , 'DVRLK'    , 'DYBNK'    , 
                'DGRVK'    , 'DENFA'    , 'DNFIN'    , 'DZY DZYMK', 'DENIZ DNZ', 'DSTKF'    , 
                'DTBMK'    , 'DTRND'    , 'DFKTR'    , 'DNYVA'    , 'EKER'     , 'EKOFA'    , 
                'EKOVR'    , 'EMIRV'    , 'EKTVK'    , 'EMVAR'    , 'ERGLI'    , 'EUKYO'    , 
                'EUYO'     , 'ETYAT'    , 'FSDAT'    , 'FIBAF'    , 'FBB FBBNK', 'GAPIN'    , 
                'GARFA'    , 'GARFL'    , 'GRNYO'    , 'GEDIK'    , 'GLCVY'    , 'GLB GLBMD', 
                'GGBVK'    , 'GSIPD'    , 'HALKF'    , 'HLVKS'    , 'HALKI HLY', 'HDFFL'    , 
                'HDFYB HYB', 'HEPFN'    , 'HUZFA'    , 'ICB ICBCT', 'IAZ INVAZ', 'INALR'    , 
                'INFO IYF' , 'ISTFK'    , 'ISFAK'    , 'ISFIN'    , 'ISMEN IYM', 'ISYAT'    , 
                'KLVKS'    , 'KATVK'    , 'KNTFA'    , 'KFKTF'    , 'KOCFN'    , 'KORTS'    , 
                'KTKVK'    , 'KTSVK'    , 'LVTVK'    , 'LIDFA'    , 'MRBAS MRS', 'MRMAG'    , 
                'MEKMD MSA', 'MRBKF'    , 'MBFTR'];